version: "3.8"

# Development environment override
services:
  php:
    build:
      context: ./api
      target: php_dev
    volumes:
      - ./api:/srv/app
      - ./api/docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  nginx:
    build:
      context: api/
      target: nginx_base
    volumes:
      - ./api/public:/srv/app/public:ro
  
  
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: !ChangeMe!
      POSTGRES_DB: app
  

  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
